[package]
name = "orbital_calculator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.0"
ggez = "0.9.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
nalgebra = "0.32"
mint = "0.5"
